language: node_js
sudo: false
node_js:
  - "8"
before_install:
  - npm i -g npm
before_script:
  - npm run build
install:
  - npm install
script:
  - npm test
cache:
  directories:
    - "node_modules"
